# netlify.toml

[build]
  command = "npm install"
  publish = "public" # Or wherever your static frontend files are (if you have them)
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Add other dependencies like mongoose, etc., if they are not automatically bundled
  external_node_modules = ["express", "serverless-http", "mongoose", "cookie-parser", "swagger-ui-express"] 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-docs/*"
  to = "/.netlify/functions/api/:splat" # Or potentially to the root of your function
  status = 200
  force = true